### ISSUE TITLE
Tests occasionally stall and test files are created at root, and tests fail

### ISSUE THREAD

**Issue by reggieb** [EnvironmentAgency/before_commit#11]
The title of this issue describes the problem.

I think the problem is occurring because **before_commit** uses the current context to identify where to insert the files. That is, files are inserted relative to location where the command is run, rather that relative to where the before_commit files are located. See the use of `FileUtils.pwd` in [`BeforeCommit::FileManager`](https://github.com/EnvironmentAgency/before_commit/blob/master/lib/before_commit/file_manager.rb#L15)

In tests, the the current context is shifted to within `/test` so that files generated by test don't pollute the main code space.

**Comment by Cruikshanks** [comment]
Are you happy to close this @reggieb now that we've merged #12 ?
