### ISSUE TITLE
The rubocop --rails argument is always used by overcommit

### ISSUE THREAD

**Issue by Cruikshanks** [EnvironmentAgency/before_commit#18]
In the `overcommit.yml` file we set `--rails` as one of the arguments we pass to **rubocop** when running it. However we don't just use **before_commit** in just Rails apps, but also gems and engines.

Using this flag leads to false positives being found. For example use `puts` in your gem and then run `rubocop --rails'` will cause the following to be reported

```text
lib/copy_kit/node_view_to_rails.rb:116:7: C: Do not write to stdout. Use Rails' logger if you want to log.
      puts "Completed conversion to Rails view with localization #{yaml_file}\n"
```

Much like the tweak to only run [brakeman](http://brakemanscanner.org/) if `bin/rails` is found, we also need to only use this flag if we are in a rails app.

**Comment by reggieb** [comment]
The erb parsing of yamls fixes this issue by allowing overcommit.yml to me modified depending on the presence of `Rails` in the environment. See https://github.com/EnvironmentAgency/before_commit/blob/master/source/.overcommit.yml#L32
