### ISSUE TITLE
Brakeman not needed if project is non-rails

### ISSUE THREAD

**Issue by woodpigeon** [EnvironmentAgency/before_commit#2]
If the project is not a rails app, e.g. its a gem, brakeman fails.
Setting `enabled: false` in `.overcommit.yml` fixes this. I couldn't see a way make running brakeman conditional inside overcommit.yml - eg by checking for the existence of bin/rails 
Could write a custom brakeman task based on the [original](https://github.com/brigade/overcommit/blob/master/lib/overcommit/hook/pre_commit/brakeman.rb) but add a check for bin/rails maybe. Not sure.

**Comment by Cruikshanks** [comment]
Have labelled this as an enhancement. When we originally thought of this we were thinking in terms of a *rails* app but as quite rightly pointed out we actually intend to use this in repos which are engines, gems, or possibly in the future just simply ruby scripts.

So leaving this with @reggieb to review what can be done to conditionally set *Brakeman* (with an eye to possibly conditionally setting others depending on the nature of the repo) when installing and updating *BeforeCommit* into a repo.
